export { default as HomePage } from './HomePage'
export { default as Auth } from './Auth'
export { default as RoomPage } from './RoomPage'
export { default as PostPage } from './PostPage'
export { default as MyRoomPage } from './MyRoomPage'
export { default as AboutPage } from './AboutPage'
export { default as MyReservationsPage } from './MyReservationsPage'
export { default as SingleRoomPage } from './SingleRoomPage'
export { default as SingleMyRoomPage } from './SingleMyRoomPage'
export { default as SingleReservationsPage } from './SingleReservationsPage'
export { default as DashboardPage } from './DashboardPage'
export { default as UserProfilePage } from './UserProfilePage'

export { default as PageLoader } from './PageLoader'
export { default as Page404 } from './Page404'